version: '3.8'
services:
  wearable-simulator:
    build:
      context: .
      dockerfile: Dockerfile
    image: wearable-simulator
    ports:
      - "5000:5000"
    environment:
      - APP_HOST='0.0.0.0'
      - APP_PORT=5000
      - APP_PUBLIC_URL='http://0.0.0.0:5000'
