version: '3.8'
services:
  wearable-simulator:
    container_name: wearable-simulator
    build:
      context: .
      dockerfile: Dockerfile
    image: wearable-simulator
    ports:
      - "5000:5000"
    environment:
      - APP_HOST=127.0.0.1
      - APP_PORT=5000
      - APP_PUBLIC_URL='http://127.0.0.1:5000'
